---

- name: Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-passlib
    - apache2-utils

- name: Creating htpasswd folder
  file:
    dest: "{{ htpasswd_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
