---

- name: Adding htpasswd files
  htpasswd:
    path: "{{ htpasswd_path }}/{{ item.0.name }}"
    name: "{{ item.1.name }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt|default(omit) }}"
    owner: root
    group: root
    mode: 0644
  with_subelements:
    - htpasswd
    - users
